feat: 添加no-typos检查规则
ecomfe/reskript pull request #181
Opened 2021-10-20 02:02 UTC by yhkkkkk

2021-10-20 03:19 UTC, otakustay requested changes

2021-10-20 03:19 UTC, otakustay commented on packages/eslint-plugin/rules/no-typos/index.js
> +        if (!commonTypoWords.includes(lowerCaseWord)) {
这东西直接用`typos.hasOwnProperty`就行了吧，`includes`多慢啊

2021-10-20 03:19 UTC, otakustay commented on packages/config-lint/src/rules/eslint.ts
> +        '@reskript/no-typos': 'warn',
规则的名字再让我想想

2021-10-20 03:19 UTC, otakustay commented on packages/eslint-plugin/rules/no-typos/index.js
> +// 这里默认变量名都是驼峰式命名，其他命名风格暂不考虑
至少`THIS_IS_A_CONSTANT`的形式得支持上，也不麻烦

2021-10-20 03:19 UTC, otakustay commented on packages/eslint-plugin/rules/no-typos/index.js
> +// 这里默认变量名都是驼峰式命名，其他命名风格暂不考虑
此处有考虑`XMLHttpRequest`这种连续大写的吗？有没有对应的用例

2021-10-20 03:19 UTC, otakustay commented on packages/eslint-plugin/rules/no-typos/index.js
> +    const expectWords = words.map(word => {
建议把这个callback提外面去独立个函数，我预感这里面有很大的强化空间的，比如支持更多形态的大小写组合、加上memoize等

2021-10-20 03:19 UTC, otakustay commented on packages/eslint-plugin/rules/no-typos/index.js
> +                if (name !== expectName) {
字符串的`===`也是有性能消耗的，考虑到这个规则的处理量非常大，是否能在`getExpectSpelling`里做些手脚，让它通过的时候能返回`true`这种比较性能更高的类型

2021-11-01 07:11 UTC, otakustay requested changes

2021-11-01 07:11 UTC, otakustay commented on packages/eslint-plugin/rules/spell-check/index.js
> +    if (type === 'capital') {
此处用`switch`会更直观易读

2021-11-01 07:11 UTC, otakustay commented on packages/eslint-plugin/rules/spell-check/index.js
> +    let hasTypo = false;
我们在这里留个注释，说明下我们是为了追求性能才做的这个“并不漂亮”的代码

2021-11-01 07:11 UTC, otakustay commented on packages/eslint-plugin/rules/spell-check/walker.js
> +    type() {
这个方法的名字不直观，可以用`currentCharCase`之类的

2021-11-01 07:11 UTC, otakustay commented on packages/eslint-plugin/rules/spell-check/walker.js
> +            this.resolveCurrent('lowercase', false);
有字符不是正常的英文不代表它一定是小写的吧，比如`123HELLO`就是一个upper的？

2021-11-02 13:26 UTC, yhkkkkk commented on packages/eslint-plugin/rules/spell-check/walker.js
> +            this.resolveCurrent('lowercase', false);
这里默认的case是lowercase，如果是123HELLO这种的话，匹配到H时会转为uppercase，同时会多处理一次前面的lowercase，没有必要，所以增加一个 unknown 状态吧

2021-11-03 03:51 UTC, otakustay commented
`spell-check`的检查规则会把相应的test文件都查出lint错误来，你得配置一下或加上disable来解决这个问题，不然无法合入

2021-11-03 09:48 UTC, yhkkkkk commented
嗯，我看是因为检查typos.js文件了，我给disable掉啦

2021-11-03 09:55 UTC, otakustay approved these changes

2021-11-03 10:02 UTC, otakustay commented
lint还有一些问题，其它的包里的代码同样有拼写错误，你参考CI的输出一起修复一下吧……

2021-11-03 12:26 UTC, yhkkkkk commented
嗯，前面竟然没看到。。。

2021-11-03 12:40 UTC, merged