feat(lint): 添加useless-memoized-hooks检查规则
ecomfe/reskript pull request #192
Opened 2021-11-04 09:54 UTC by dongggcom

2021-11-04 11:26 UTC, otakustay commented
情先细化下文档中的说明，什么是过度包装

2021-11-13 06:42 UTC, otakustay commented on site/docs/advanced/lint-rules.md
> +检查过度包装的 `hooks`。识别仅有一个 `dependency` 且是调用函数时，进行优化。目的是减少构建 `memoized function` 的开销。
`reSKRipt`的文档，中英文中间都是不加空格的，要不统一不加吧

这个说法应该不准确，我理解同时满足以下条件才行：

1. 是`useCallback`。`useMemo`是不存在这情况的
2. `dependencies`数组仅依赖一个函数
3. 函数体仅有对这个函数的调用
4. 调用没有传递任何参数

2021-11-13 07:15 UTC, otakustay commented on packages/eslint-plugin/rules/useless-memoized-hooks/__tests__/fixtures/only-depend-on-callee-invalid.output.js
> +const handleCancel = hideModal;
如果这玩意会自动修复，且修复后会留下这么孤零零的一行奇怪的赋值，那开发者依赖自动修复，代码不是会越来越奇怪了……

2021-11-13 07:18 UTC, otakustay commented on packages/eslint-plugin/rules/useless-memoized-hooks/index.js
> +            description: 'Detect memoized hook is used in only one call expression',
`Call to useCallback is useless`

2021-11-18 02:16 UTC, dongggcom commented on packages/eslint-plugin/rules/useless-memoized-hooks/__tests__/fixtures/only-depend-on-callee-invalid.output.js
> +const handleCancel = hideModal;
确实... autofix 我去了吧

2021-11-18 02:17 UTC, dongggcom commented on site/docs/advanced/lint-rules.md
> +检查过度包装的 `hooks`。识别仅有一个 `dependency` 且是调用函数时，进行优化。目的是减少构建 `memoized function` 的开销。
这块我调整下

2021-12-06 04:50 UTC, otakustay requested changes
少了一些用例：

```js
useCallback(
  function () {
    return hideModal(); // 注意这里必须有return
  },
  [hideModal]
);
```

```js
useCallback(
  () => {
    return hideModal();
  },
  [hideModal]
);
```

另外下面的应该是合法的，不能触发规则：

```js
useCallback(
  () => {
    hideModal();
  },
  [hideModal]
);
```

2021-12-06 04:50 UTC, otakustay commented on packages/config-lint/src/rules/eslint.ts
> +        '@reskript/useless-memoized-hooks': 'warn',
再调整一下这个名字吧，用`useless-memo-hooks`，和`useMemo`对应一下

2021-12-06 04:50 UTC, otakustay commented on packages/eslint-plugin/rules/useless-memoized-hooks/index.js
> +                expression && depNode.elements[0] && expression.callee.name === depNode.elements[0].name
把`depNode.elements[0]`拿到外面起个变量名，让读代码的人知道这是个啥东西

2021-12-06 04:50 UTC, otakustay commented on packages/eslint-plugin/rules/useless-memoized-hooks/index.js
> +const isUseCallbackHook = name => name === 'useCallback';
我们不检查`useMemo`吗？

```js
const memo = useMemo(
  () => value,
  [value]
);
```

2021-12-06 13:16 UTC, otakustay commented on packages/config-lint/src/rules/eslint.ts
> +        '@reskript/useless-memoized-hooks': 'warn',
更新一下，叫`no-useless-memo-hooks`

2021-12-15 03:40 UTC, dongggcom commented on packages/eslint-plugin/rules/useless-memoized-hooks/index.js
> +const isUseCallbackHook = name => name === 'useCallback';
get it

2022-02-07 08:02 UTC, merged