feat: 添加 react 代码性能优化转换
ecomfe/reskript pull request #261
Opened 2022-02-17 11:57 UTC by LeuisKen

参考如下 issue 引入了两个 babel plugin：

- https://github.com/facebook/react/issues/3226
- https://github.com/facebook/react/issues/3228

用本地项目测了一下，terser 产物的体积会有非常小的增加，不会导致什么实质影响。

2022-02-22 05:10 UTC, otakustay commented
解决一下CI问题，应该是少类型定义

2022-02-23 05:25 UTC, otakustay requested changes

2022-02-23 05:25 UTC, otakustay commented on packages/config-babel/src/parseOnly.ts
> +        // https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements
这2个插件不应该加在`parseOnly`里，`parseOnly`顾名思义是只用来做语法解析的，比如给eslint用。

babel配置一共有3层：

1. `parseOnly`：只做解析，不做转换用，给lint、jest等工具
2. `transformMinimal`：做代码转换，但不做激进的优化，基本只用于`skr babel`输出
3. `transform`：全量的优化，代码在`index.ts`里

所以你需要在那边加这些插件

2022-02-23 07:51 UTC, LeuisKen commented on packages/config-babel/src/parseOnly.ts
> +        // https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements
好的，不过好奇怪为啥 CI 又挂了

2022-02-23 08:16 UTC, otakustay commented on packages/config-babel/src/parseOnly.ts
> +        // https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements
超时了，可以先不管

2022-02-24 04:10 UTC, otakustay commented
下次提交的时候记得rebase master一下，我把CI修了把，应该更容易跑通了

2022-02-24 06:29 UTC, merged